name: Python Checker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LOG_FILE: /home/runner/work/module_registry/log.txt
      REPO_PATH: /home/runner/work/module_registry

    strategy:
      matrix:
        node-version: [18.17.x]
        python-version: [3.8]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Node.js dependencies
        run: npm install

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python script
        run: python3 ECE461-Part-1-CLI-Checker/checker.py



      - name: Show current directory
        run: pwd
      - name: List files
        run: ls -la
      - name: Run install
        run: ./run install
      - name: Run test
        run: ./run test
